### ISSUE TITLE
Move tagging to patternfly-react

### ISSUE THREAD

**Issue by karelhala** [ManageIQ/react-ui-components#5]
As tagging is generic and could be shared between other teams we should probably expose it into https://github.com/patternfly/patternfly-react, so once we are satisfied with how it works and UX gives us proper styleguide we have to move it to patternfly react repo.

### Tagging component
Currently this component is developped https://github.com/ManageIQ/react-ui-components/pull/3

**Comment by chessbyte** [comment]
Closed via #3
